networks:
  mcp:


services:

  runtime:
    entrypoint: npm
    command: run dev
    build:
      context: .
      dockerfile: Dockerfile
    image: muka/agents-test
    networks:
      - mcp
    volumes:
      - ./:/app
